version: '2'

services:
  app:
    image: 'Portfolio_1-0.0.1-SNAPSHOT.jar:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://bcxls5zdbnh2iahjtbaw-mysql.services.clever-cloud.com:3306/compose-mysql
      - SPRING_DATASOURCE_USERNAME=ubuzgawymr00rpia
      - SPRING_DATASOURCE_PASSWORD=2Lfwgy1EO3YmHGpVCOHk
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - 3306:3306
          
  db:
    image: 'mysql:8.0.30'
    container_name: db
    environment:
      - POSTGRES_USER=ubuzgawymr00rpia
      - POSTGRES_PASSWORD=2Lfwgy1EO3YmHGpVCOHk